[project]
name = "pearson-pandas-best-practices"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "notebook>=7.4.5",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "seaborn>=0.13.2",
]
